In [1]:
import numpy as np

In [2]:
# DNA sequences
S1 = np.array(['A','T','G','G','A','T','T','A','C','A','C','A','C','G','G','A','T','G','T','A','C','A',
               'A','T','A','A','T','G','C','T','A','A','G','C','G'])
S2 = np.array(['A','T','G','A','G','C','T','-','-','A','C','A','C','G','A','A','T','T','T','A','C','A','T','T',
               '-','A','G','G','A','C','A','T','G','C','G'])
S3 = np.array(['A','T','G','A','T','A','A','A','C','A','C','A','G','G','G','A','T','G','T','T','C','A',
               'A','T','A','A','T','G','C','T','A','G','G','C','G'])
S4 = np.array(['A','T','G','A','T','A','A','-','-','-','-','A','C','G','G','A','T','T','T','T','C','A','A','T','A','A',
               'G','G','C','T','T','G','G','C','A'])

sequence_array = np.array([S1, S2, S3, S4])

In [54]:
# function to compute pairwise distance while ignoring INDELS

def pairwise_distance_no_indel(sequence_1, sequence_2):
    # calculates the no. of indels
    indels_1 = 0
    for i in range(len(sequence_1)):
        if sequence_1[i] == str('-'):
            indels_1 = indels_1 + 1
    
    indels_2 = 0       
    for j in range(len(sequence_2)):
        if sequence_2[j] == str('-'):
            indels_2 = indels_2 +1
            
    if indels_1 > indels_2:
        indels = indels_1
    else:
        indels = indels_2
    
    N = 0
    L = len(sequence_1) - indels
    
    for k in range(len(sequence_1)):
        if sequence_1[k] == sequence_2[k]:
            pass
        elif sequence_1[k] == str('-'):
            pass
        elif sequence_2[k] == str('-'):
            pass
        else:
            N = N+1
            
    return ((N)/L)

In [55]:
# function to compute pairwise distance using INDELS

def pairwise_distance_with_indel(sequence_1, sequence_2):
   
    N = 0
    L = len(sequence_1)
    
    for k in range(len(sequence_1)):
        if sequence_1[k] == sequence_2[k]:
            pass
        else:
            N = N+1
            
    return ((N)/L)

In [98]:
# program that computes the full matrix of pairwise distances for all four sequences

def matrix_distance(x):
    
    distance = []
    
    for i in range(4):
        sequence_1 = sequence_array[i]
        
        for j in range(4):
            sequence_2 = sequence_array[j]
            distance =np.append(distance, x(sequence_1,sequence_2))
    
    return print('Matrix of pairwise distances'), print(np.reshape(distance, (4,4)))

In [99]:
matrix_distance(pairwise_distance_no_indel)

Matrix of pairwise distances
[[ 0.          0.3125      0.2         0.32258065]
 [ 0.3125      0.          0.375       0.35483871]
 [ 0.2         0.375       0.          0.16129032]
 [ 0.32258065  0.35483871  0.16129032  0.        ]]


(None, None)

In [100]:
matrix_distance(pairwise_distance_with_indel)

Matrix of pairwise distances
[[ 0.          0.37142857  0.2         0.4       ]
 [ 0.37142857  0.          0.42857143  0.4       ]
 [ 0.2         0.42857143  0.          0.25714286]
 [ 0.4         0.4         0.25714286  0.        ]]


(None, None)

In [81]:
# Manual checks for the no indel program

In [82]:
# S1 vs S2 manually found to be 0.3125
pairwise_distance_no_indel(S1,S2)

0.3125

In [83]:
#S2 vs S4 manually found to be 0.354
pairwise_distance_no_indel(S2,S4)

0.3548387096774194

In [84]:
# Manual checks for the indel program

In [85]:
# S1 vs S2 manually found to be 0.3714
pairwise_distance_with_indel(S1,S2)

0.37142857142857144

In [86]:
# S2 vs S4 manually found to be 0.4
pairwise_distance_with_indel(S2,S4)

0.4